--- имена клиентов, их город, имена менеджерова по продажам, и их город, где сумма сделки была больше 10000
SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY
FROM CUSTOMER
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
JOIN SALESMAN ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
WHERE DEAL.AMOUNT > 10000;


--- имена клиентов которые делали сделки в 2017-2018 годах
SELECT CUSTOMER.CUSTNAME
FROM CUSTOMER
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
WHERE DEAL.DATE_ BETWEEN TO_DATE('2017-01-01','YYYY-MM-DD') AND TO_DATE('2018-12-31','YYYY-MM-DD');


--- имя лучшего менеджера по продажам по сумме сделок за август 2017 года, выводить несколько имен, если таких менеджеров несколько
SELECT NAME
FROM (SELECT SUM(DEAL.AMOUNT) AS RES, SALESMAN.NAME
    FROM SALESMAN
    INNER JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER. SALESMAN_ID
    INNER JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
    WHERE DEAL.DATE_ BETWEEN TO_DATE('2017-08-01','YYYY-MM-DD') AND TO_DATE('2017-08-31','YYYY-MM-DD')
    GROUP BY SALESMAN.NAME)
WHERE RES = (SELECT MAX(RES)
    FROM (SELECT SUM(DEAL.AMOUNT) AS RES, SALESMAN.NAME
        FROM SALESMAN
        INNER JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER. SALESMAN_ID
        INNER JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
        WHERE DEAL.DATE_ BETWEEN TO_DATE('2017-08-01','YYYY-MM-DD') AND TO_DATE('2017-08-31','YYYY-MM-DD')
        GROUP BY SALESMAN.NAME));