CREATE TABLE DEAL (
 DEAL_ID NUMBER PRIMARY KEY,
 CUSTOMER_ID NUMBER,
 CONSTRAINT CUSTOMER_DEAL_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
 AMOUNT NUMBER NOT NULL,
 DATE_ TIMESTAMP NOT NULL
);