CREATE TABLE FORUM_POLLS_OPTIONS_VOTES(
 ID NUMBER,
 CONSTRAINT POLLS_OPTIONS_VOTE_PK PRIMARY KEY(ID),
 ID_POLL_OPTION NUMBER,
 CONSTRAINT POLL_OPTION_FK FOREIGN KEY(ID_POLL_OPTION) REFERENCES FORUM_POLLS_OPTIONS(ID),
 ID_USER NUMBER,
 CONSTRAINT USER_FK FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
 DATE_POLL_OPTION_VOTE TIMESTAMP,
 IP NVARCHAR2(20)
);