CREATE TABLE FORUM_POSTS(
 ID NUMBER,
 CONSTRAINT FORUM_POST_PK PRIMARY KEY(ID),
 ID_SUBCATEGORY NUMBER,
 CONSTRAINT ID_SUBCATEGORY_FK FOREIGN KEY(ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES(ID),
 ID_USER NUMBER,
 CONSTRAINT ID_USER_FK FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
 PARENT_POST NUMBER,
 CONSTRAINT PARENT_POST_FK FOREIGN KEY(PARENT_POST) REFERENCES FORUM_POSTS(ID),
 TITLE NVARCHAR2(90),
 CONTENT CLOB,
 IS_POOL NUMBER(1),
 DATE_POST TIMESTAMP,
 IP NVARCHAR2(20)
);