CREATE TABLE SUPPLIERS(
 SUPPLIER_ID NUMBER,
 CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID),
 COMPANY_NAME NVARCHAR2(50),
 CONTACT_NAME NVARCHAR2(50),
 ADDRESS NVARCHAR2(50),
 CITY NVARCHAR2(20),
 REGION NVARCHAR2(20),
 POSTAL_CODE NUMBER,
 COUNTRY NVARCHAR2(20),
 PHONE NUMBER,
 FAX NUMBER,
 HOME_PAGE NVARCHAR2(100)
);