CREATE TABLE CUSTOMERS(
 CUSTOMER_ID NUMBER,
 CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
 COMPANY_NAME NVARCHAR2(50),
 CONTACT_NAME NVARCHAR2(20),
 CONTACT_TYTLE NVARCHAR2(30),
 ADDRESS NVARCHAR2(50),
 CITY NVARCHAR2(20),
 REGION NVARCHAR2(20),
 POSTAL_CODE NUMBER,
 COUNTRY NVARCHAR2(20),
 PHONE NUMBER,
 FAX NUMBER
);