CREATE TABLE EMPLOYEES(
 EMPLOYEE_ID NUMBER,
 LAST_NAME NVARCHAR2(20),
 FIRST_NAME NVARCHAR2(20),
 TYTLE NVARCHAR2(30),
 TYTLE_OF_COURTESY NVARCHAR2(50),
 BIRTH_DATE TIMESTAMP,
 HIRE_DATE TIMESTAMP,
 ADDRESS NVARCHAR2(50),
 CITY NVARCHAR2(20),
 REGION NVARCHAR2(20),
 POSTAL_CODE NUMBER,
 COUNTRY NVARCHAR2(20),
 PHONE NUMBER,
 EXTENSION NVARCHAR2(20),
 PHOTO NVARCHAR2(50),
 NOTES NVARCHAR2(100),
 REPORTS_TO CLOB
);