CREATE TABLE PRODUCTS(
 PRODUCT_ID NUMBER,
 CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
 PRODUCT_NAME NVARCHAR2(50),
 SUPPLIER_ID NUMBER,
 CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
 CUTEGORY_ID NUMBER,
 CONSTRAINT CUTEGORY_FK FOREIGN KEY (CUTEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
 QUANTITY_PER_UNIT NUMBER,
 UNIT_PRICE NUMBER(10,2),
 UNITS_IN_STOCK NUMBER,
 UNITS_ON_ORDER NUMBER,
 REORDER_LEVEL NUMBER,
 DISCONTINUED NUMBER
);