CREATE TABLE HOTEL(
 ID NUMBER,
 CONSTRAINT HOTEL_PK PRIMARY KEY(ID),
 COUNTRY NVARCHAR2(50) DEFAULT 'N/A',
 CONSTRAINT COUNTRY_CHECK CHECK (COUNTRY != 'Romania' OR COUNTRY != 'Belgium' OR COUNTRY != 'China' OR COUNTRY != 'Ukraine'),
 CITY NVARCHAR2(50) NOT NULL,
 STREET NVARCHAR2(50)
);