--ORDER не дало создать
CREATE TABLE ORDER_(
 ID NUMBER,
 CONSTRAINT ORDER_PK PRIMARY KEY(ID),
 CONSTRAINT ID_CHECK CHECK (ID <= 10000),
 USER_ID NUMBER UNIQUE,
 ROOM_ID NUMBER UNIQUE,
 DATE_FROM TIMESTAMP,
 DATE_TO TIMESTAMP,
 MONEY_PAID NUMERIC(5,2)
);