select PRODUCT_NAME, PRICE from ORDERS
--GROUP BY PRODUCT_NAME;
--ORDER BY PRODUCT_NAME ASC;
ORDER BY PRICE DESC;

select COUNT(*) FROM ORDERS
WHERE PRICE > 200;

select * FROM ORDERS
WHERE EXISTS (SELECT * FROM PRODUCT WHERE NAME = ORDERS.PRODUCT_NAME);

SELECT * FROM ORDERS
WHERE EXISTS (SELECT * FROM PRODUCT WHERE NAME = ORDERS.PRODUCT_NAME AND COST_PRICE > ORDERS.PRICE);

SELECT * FROM ORDERS
WHERE PRICE BETWEEN 150 AND 1000;

SELECT * FROM ORDERS
WHERE DATE_ORDERED BETWEEN TO_DATE('01-05-2017') AND TO_DATE('10-05-2017');

SELECT *FROM ORDERS
WHERE PRODUCT_NAME LIKE '%toy%';